<?xml version="1.0" encoding="utf-8"?>
<Database Name="dev_azillion_db" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=63.211.192.184;Initial Catalog=dev_azillion_db;Persist Security Info=True;User ID=azillionhomes" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AZillionHomesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Agency" Member="Agencies">
    <Type Name="Agency">
      <Column Name="AgencyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Website" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="OwnerUserInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvitationCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="State_Agency" Member="State" ThisKey="StateID" OtherKey="StateID" Type="State" IsForeignKey="true" />
      <Association Name="UserInfo_Agency" Member="UserInfo" ThisKey="OwnerUserInfoID" OtherKey="UserInfoID" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Zipcode" Member="Zipcodes">
    <Type Name="Zipcode">
      <Column Name="ZipcodeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Zipcode" Member="Zipcode1" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Abbreviation" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AlertHistory" Member="AlertHistories">
    <Type Name="AlertHistory">
      <Column Name="AlertHistoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AlertName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateStarted" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DateFinished" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NumRecipients" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserIDs" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Announcement" Member="Announcements">
    <Type Name="Announcement">
      <Column Name="AnnouncementID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Teaser" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="UserInfo_Announcement" Member="UserInfo" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CellPhoneProvider" Member="CellPhoneProviders">
    <Type Name="CellPhoneProvider">
      <Column Name="CellPhoneProviderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CMSPage" Member="CMSPages">
    <Type Name="CMSPage">
      <Column Name="CMSPageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageTitle" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MetaDescription" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="MetaKeywords" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="PageContent" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Continent" Member="Continents">
    <Type Name="Continent">
      <Column Name="ContinentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Continent_Country" Member="Countries" ThisKey="ContinentID" OtherKey="ContinentID" Type="Country" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="CountryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Capital" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ECommerceSafe" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Language" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContinentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Abbreviation" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Country_State" Member="States" ThisKey="CountryID" OtherKey="CountryID" Type="State" />
      <Association Name="Continent_Country" Member="Continent" ThisKey="ContinentID" OtherKey="ContinentID" Type="Continent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Coupon" Member="Coupons">
    <Type Name="Coupon">
      <Column Name="CouponID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="CouponCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CouponType" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CouponAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalUses" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Used" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expires" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FieldType" Member="FieldTypes">
    <Type Name="FieldType">
      <Column Name="FieldTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RenderControl" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EditControl" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ValueFormatID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FieldType_FormField" Member="FormFields" ThisKey="FieldTypeID" OtherKey="FieldTypeID" Type="FormField" />
      <Association Name="ValueFormat_FieldType" Member="ValueFormat" ThisKey="ValueFormatID" OtherKey="ValueFormatID" Type="ValueFormat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Form" Member="Forms">
    <Type Name="Form">
      <Column Name="FormID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RequiresPrice" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RequiresDate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RequiresBedBath" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Form_FormEntry" Member="FormEntries" ThisKey="FormID" OtherKey="FormID" Type="FormEntry" />
      <Association Name="Form_FormListingType" Member="FormListingTypes" ThisKey="FormID" OtherKey="FormID" Type="FormListingType" />
      <Association Name="Form_FormSection" Member="FormSections" ThisKey="FormID" OtherKey="FormID" Type="FormSection" />
    </Type>
  </Table>
  <Table Name="dbo.FormDocument" Member="FormDocuments">
    <Type Name="FormDocument">
      <Column Name="FormDocumentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormEntryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Filename" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FormEntry_FormDocument" Member="FormEntry" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormEntry" Member="FormEntries">
    <Type Name="FormEntry">
      <Column Name="FormEntryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AZHID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ListingTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StreetNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StreetName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(5000) NOT NULL" CanBeNull="false" />
      <Column Name="Directions" Type="System.String" DbType="VarChar(5000) NOT NULL" CanBeNull="false" />
      <Column Name="TotalRooms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bedrooms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bathrooms" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SearchableFields" Type="System.String" DbType="VarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="Entry" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Completed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Paid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Expires" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EventStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="FormEntry_FormDocument" Member="FormDocuments" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormDocument" />
      <Association Name="FormEntry_FormEntryCache" Member="FormEntryCaches" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormEntryCache" />
      <Association Name="FormEntry_FormFieldData" Member="FormFieldDatas" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormFieldData" />
      <Association Name="FormEntry_FormImage" Member="FormImages" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormImage" />
      <Association Name="FormEntry_FormView" Member="FormViews" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormView" />
      <Association Name="FormEntry_OpenHouseDate" Member="OpenHouseDates" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="OpenHouseDate" />
      <Association Name="FormEntry_SavedFormEntry" Member="SavedFormEntries" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="SavedFormEntry" />
      <Association Name="FormEntry_SavedSearchFormEntryHistory" Member="SavedSearchFormEntryHistories" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="SavedSearchFormEntryHistory" />
      <Association Name="Form_FormEntry" Member="Form" ThisKey="FormID" OtherKey="FormID" Type="Form" IsForeignKey="true" />
      <Association Name="ListingType_FormEntry" Member="ListingType" ThisKey="ListingTypeID" OtherKey="ListingTypeID" Type="ListingType" IsForeignKey="true" />
      <Association Name="State_FormEntry" Member="State" ThisKey="StateID" OtherKey="StateID" Type="State" IsForeignKey="true" />
      <Association Name="UserInfo_FormEntry" Member="UserInfo" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormEntryArchive" Member="FormEntryArchives">
    <Type Name="FormEntryArchive">
      <Column Name="FormEntryArchiveID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AZHID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FormType" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ListingType" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StreetNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StreetName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(5000) NOT NULL" CanBeNull="false" />
      <Column Name="Directions" Type="System.String" DbType="VarChar(5000) NOT NULL" CanBeNull="false" />
      <Column Name="Bedrooms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bathrooms" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SearchableFields" Type="System.String" DbType="VarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="Entry" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Completed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Paid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Expires" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TotalViews" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReasonedRemoved" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FormEntryCache" Member="FormEntryCaches">
    <Type Name="FormEntryCache">
      <Column Name="FormEntryCacheID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormEntryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CachedBody" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CachedHeader" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="FormEntry_FormEntryCache" Member="FormEntry" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormField" Member="FormFields">
    <Type Name="FormField">
      <Column Name="FormFieldID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FieldTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormSectionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultValue" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="AllowedValues" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Required" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ToolTip" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Regex" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Suffix" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Searchable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="FormField_FormFieldData" Member="FormFieldDatas" ThisKey="FormFieldID" OtherKey="FormFieldID" Type="FormFieldData" />
      <Association Name="FieldType_FormField" Member="FieldType" ThisKey="FieldTypeID" OtherKey="FieldTypeID" Type="FieldType" IsForeignKey="true" />
      <Association Name="FormSection_FormField" Member="FormSection" ThisKey="FormSectionID" OtherKey="FormSectionID" Type="FormSection" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormFieldData" Member="FormFieldDatas">
    <Type Name="FormFieldData">
      <Column Name="FormFieldDataID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormFieldID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormEntryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Association Name="FormEntry_FormFieldData" Member="FormEntry" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormEntry" IsForeignKey="true" />
      <Association Name="FormField_FormFieldData" Member="FormField" ThisKey="FormFieldID" OtherKey="FormFieldID" Type="FormField" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormImage" Member="FormImages">
    <Type Name="FormImage">
      <Column Name="FormImageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormEntryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Caption" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Filename" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FormEntry_FormImage" Member="FormEntry" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormListingType" Member="FormListingTypes">
    <Type Name="FormListingType">
      <Column Name="IndexID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ListingTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Form_FormListingType" Member="Form" ThisKey="FormID" OtherKey="FormID" Type="Form" IsForeignKey="true" />
      <Association Name="ListingType_FormListingType" Member="ListingType" ThisKey="ListingTypeID" OtherKey="ListingTypeID" Type="ListingType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormSection" Member="FormSections">
    <Type Name="FormSection">
      <Column Name="FormSectionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FirstPage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FormSection_FormField" Member="FormFields" ThisKey="FormSectionID" OtherKey="FormSectionID" Type="FormField" />
      <Association Name="Form_FormSection" Member="Form" ThisKey="FormID" OtherKey="FormID" Type="Form" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FormViews" Member="FormViews">
    <Type Name="FormView">
      <Column Name="ViewID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormEntryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ViewDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ViewIP" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="FormEntry_FormView" Member="FormEntry" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ListingType" Member="ListingTypes">
    <Type Name="ListingType">
      <Column Name="ListingTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HasPrice" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MonthlyPrice" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasDate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ListingType_FormEntry" Member="FormEntries" ThisKey="ListingTypeID" OtherKey="ListingTypeID" Type="FormEntry" />
      <Association Name="ListingType_FormListingType" Member="FormListingTypes" ThisKey="ListingTypeID" OtherKey="ListingTypeID" Type="FormListingType" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Teaser" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ExternalUrl" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="UserInfo_New" Member="UserInfo" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OpenHouseDate" Member="OpenHouseDates">
    <Type Name="OpenHouseDate">
      <Column Name="OpenHouseDateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormEntryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="FormEntry_OpenHouseDate" Member="FormEntry" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentProfile" Member="PaymentProfiles">
    <Type Name="PaymentProfile">
      <Column Name="PaymentProfileID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AuthPaymentProfileID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CardType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CardNum" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="UserInfo_PaymentProfile" Member="UserInfo" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Price" Member="Prices">
    <Type Name="Price">
      <Column Name="PriceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Display" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SavedFormEntry" Member="SavedFormEntries">
    <Type Name="SavedFormEntry">
      <Column Name="SavedFormEntryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FormEntryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="FormEntry_SavedFormEntry" Member="FormEntry" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormEntry" IsForeignKey="true" />
      <Association Name="UserInfo_SavedFormEntry" Member="UserInfo" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SavedSearch" Member="SavedSearches">
    <Type Name="SavedSearch">
      <Column Name="SavedSearchID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SearchName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Criteria" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastUsed" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EmailListings" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="SavedSearch_SavedSearchFormEntryHistory" Member="SavedSearchFormEntryHistories" ThisKey="SavedSearchID" OtherKey="SavedSearchID" Type="SavedSearchFormEntryHistory" />
      <Association Name="UserInfo_SavedSearch" Member="UserInfo" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SavedSearchFormEntryHistory" Member="SavedSearchFormEntryHistories">
    <Type Name="SavedSearchFormEntryHistory">
      <Column Name="IndexID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SavedSearchID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FormEntryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sent" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="FormEntry_SavedSearchFormEntryHistory" Member="FormEntry" ThisKey="FormEntryID" OtherKey="FormEntryID" Type="FormEntry" IsForeignKey="true" />
      <Association Name="SavedSearch_SavedSearchFormEntryHistory" Member="SavedSearch" ThisKey="SavedSearchID" OtherKey="SavedSearchID" Type="SavedSearch" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.State" Member="States">
    <Type Name="State">
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Abbreviation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Capital" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CountryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Minor" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="State_Agency" Member="Agencies" ThisKey="StateID" OtherKey="StateID" Type="Agency" />
      <Association Name="State_FormEntry" Member="FormEntries" ThisKey="StateID" OtherKey="StateID" Type="FormEntry" />
      <Association Name="State_UserInfo" Member="UserInfos" ThisKey="StateID" OtherKey="StateID" Type="UserInfo" />
      <Association Name="Country_State" Member="Country" ThisKey="CountryID" OtherKey="CountryID" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subscription" Member="Subscriptions">
    <Type Name="Subscription">
      <Column Name="SubscriptionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriptionTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserInfoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Expires" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AutoRecurring" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AuthSubscriptionID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cancelled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="SubscriptionType_Subscription" Member="SubscriptionType" ThisKey="SubscriptionTypeID" OtherKey="SubscriptionTypeID" Type="SubscriptionType" IsForeignKey="true" />
      <Association Name="UserInfo_Subscription" Member="UserInfo" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubscriptionType" Member="SubscriptionTypes">
    <Type Name="SubscriptionType">
      <Column Name="SubscriptionTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="BillingPeriod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BillingAmount" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="AllowPublic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PostsPerMonth" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SubscriptionType_Subscription" Member="Subscriptions" ThisKey="SubscriptionTypeID" OtherKey="SubscriptionTypeID" Type="Subscription" />
    </Type>
  </Table>
  <Table Name="dbo.SystemAlert" Member="SystemAlerts">
    <Type Name="SystemAlert">
      <Column Name="SystemAlertID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="SourceTables" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SelectClause" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="WhereCondition" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="OrderByClause" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="HTMLTemplateUrl" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="TextTemplateUrl" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="FrequencyHours" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ExpirationHours" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastProcessed" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="SystemAlert_SystemAlertUserHistory" Member="SystemAlertUserHistories" ThisKey="SystemAlertID" OtherKey="SystemAlertID" Type="SystemAlertUserHistory" />
    </Type>
  </Table>
  <Table Name="dbo.SystemAlertUserHistory" Member="SystemAlertUserHistories">
    <Type Name="SystemAlertUserHistory">
      <Column Name="IndexID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SystemAlertID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserInfoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sent" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="SystemAlert_SystemAlertUserHistory" Member="SystemAlert" ThisKey="SystemAlertID" OtherKey="SystemAlertID" Type="SystemAlert" IsForeignKey="true" />
      <Association Name="UserInfo_SystemAlertUserHistory" Member="UserInfo" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserInfo" Member="UserInfos">
    <Type Name="UserInfo">
      <Column Name="UserInfoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AgencyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CellPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CellPhoneProviderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CellPhoneContact" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SecurityQuestion" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="SecurityAnswer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ConfimCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UserInfo_Agency" Member="Agencies" ThisKey="UserInfoID" OtherKey="OwnerUserInfoID" Type="Agency" />
      <Association Name="UserInfo_Announcement" Member="Announcements" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="Announcement" />
      <Association Name="UserInfo_FormEntry" Member="FormEntries" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="FormEntry" />
      <Association Name="UserInfo_New" Member="News" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="New" />
      <Association Name="UserInfo_PaymentProfile" Member="PaymentProfiles" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="PaymentProfile" />
      <Association Name="UserInfo_SavedFormEntry" Member="SavedFormEntries" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="SavedFormEntry" />
      <Association Name="UserInfo_SavedSearch" Member="SavedSearches" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="SavedSearch" />
      <Association Name="UserInfo_Subscription" Member="Subscriptions" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="Subscription" />
      <Association Name="UserInfo_SystemAlertUserHistory" Member="SystemAlertUserHistories" ThisKey="UserInfoID" OtherKey="UserInfoID" Type="SystemAlertUserHistory" />
      <Association Name="State_UserInfo" Member="State" ThisKey="StateID" OtherKey="StateID" Type="State" IsForeignKey="true" />
      <Association Name="UserType_UserInfo" Member="UserType" ThisKey="UserTypeID" OtherKey="UserTypeID" Type="UserType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserPermission" Member="UserPermissions">
    <Type Name="UserPermission">
      <Column Name="UserPermissionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PermissionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Association Name="UserPermission_UserPermissionUserType" Member="UserPermissionUserTypes" ThisKey="UserPermissionID" OtherKey="UserPermissionID" Type="UserPermissionUserType" />
    </Type>
  </Table>
  <Table Name="dbo.UserPermissionUserType" Member="UserPermissionUserTypes">
    <Type Name="UserPermissionUserType">
      <Column Name="IndexID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserPermissionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserPermission_UserPermissionUserType" Member="UserPermission" ThisKey="UserPermissionID" OtherKey="UserPermissionID" Type="UserPermission" IsForeignKey="true" />
      <Association Name="UserType_UserPermissionUserType" Member="UserType" ThisKey="UserTypeID" OtherKey="UserTypeID" Type="UserType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserType" Member="UserTypes">
    <Type Name="UserType">
      <Column Name="UserTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Association Name="UserType_UserInfo" Member="UserInfos" ThisKey="UserTypeID" OtherKey="UserTypeID" Type="UserInfo" />
      <Association Name="UserType_UserPermissionUserType" Member="UserPermissionUserTypes" ThisKey="UserTypeID" OtherKey="UserTypeID" Type="UserPermissionUserType" />
    </Type>
  </Table>
  <Table Name="dbo.ValueFormat" Member="ValueFormats">
    <Type Name="ValueFormat">
      <Column Name="ValueFormatID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormatName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="ValueFormat_FieldType" Member="FieldTypes" ThisKey="ValueFormatID" OtherKey="ValueFormatID" Type="FieldType" />
    </Type>
  </Table>
</Database>